App/urls.py
"""
Urls.py includes the url configurations of the application.
"""

from django.urls import path

from App.views import Predict
from App.views import FileView
from App.views import FileDeleteView, RegisterUserPage, UpdateUserPage, AboutView, UpdateUserPage
from django.contrib.auth.views import LoginView,LogoutView

app_name = 'App'

urlpatterns = [
    path('predict/', Predict.as_view(), name='APIpredict'),
    path('upload/', FileView.as_view(), name='APIupload'),
    path('delete/', FileDeleteView.as_view(), name='APIdelete'),
    path('register/', RegisterUserPage.as_view(), name='register'),
    path('about/',AboutView.as_view(),name = 'about'),
    path('login/',LoginView.as_view(template_name = 'users/login.html'), name="login"),
    path('logout/',LogoutView.as_view(next_page = '/'),name = 'logout',kwargs = {'next_page':'/'}),
    path('update/<int:pk>',UpdateUserPage.as_view(),name = 'update'),
]

DjangoRestDeepLearning/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import re_path
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include
from App.views import UploadView
from App.views import FilesList
from App.views import IndexView
from App.views import UploadSuccessView
from App.views import SelectPredFileView
from App.views import SelectFileDelView
from App.views import FileDeleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('App/', include('App.urls',namespace='App')),
    path('', IndexView.as_view(), name='index'),

    # Urls to upload the file and confirm the upload
    path('fileupload/', UploadView.as_view(), name='upload_file'),
    path('upload_success/', UploadSuccessView.as_view(), name='upload_success'),

    # Url to select a file for the predictions
    path('fileselect/', SelectPredFileView.as_view(), name='file_select'),

    # Url to select a file to be deleted and confirm the upload
    path('filedelete/', SelectFileDelView.as_view(), name='file_delete'),
    path('delete_success/<int:pk>/', FileDeleteView.as_view(), name='delete_success'),

    # Url to list all the files in the server
    path('files_list/', FilesList.as_view(), name='files_list'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:

    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
        re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }),
    ] + urlpatterns

App/templates/about.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <h1>About The Project</h1>
    <p>The scope of this project is to create a classifier to predict the emotions of the speaker starting from an audio file.For this task, I have used 7268 samples from the RAVDESS dataset (see below to know more about the data).</p>
    <br>
    <h4>The samples comes from: </h4>
    <ul>
        <li>Audio-only files</li>
        <li>Video + audio files: I have extracted the audio from each file using the script Mp4ToWav.py that you can find in the main directory of the project.</li>
    </ul>
    <br>
    <h4>The classes we are trying to predict are the following: </h4>
    {# (0 = neutral, 1 = calm, 2 = happy, 3 = sad, 4 = angry, 5 = fearful, 6 = disgust, 7 = surprised) #}
    <ul>
        <li>0 = neutral</li>
        <li>1 = calm</li>
        <li>2 = happy</li>
        <li>3 = sad</li>
        <li>4 = angry</li>
        <li>5 = fearful</li>
        <li>6 = disgust</li>
        <li>7 = surprised</li>
    </ul>
{% endblock %}

App/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title></title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        <!-- Latest compiled and minified JavaScript -->
        <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
        <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
        <link href="https://fonts.googleapis.com/css?family=Montserrat|Russo+One&display=swap" rel="stylesheet">
    </head>
    <body class="loader">
        <nav class="navbar navbar-default techfont custom-navbar">
            <div class="container">
                <ul class = "nav navbar-nav">
                    {% if user.is_authenticated %}
                        <li><a class="navbar-brand bigbrand" href="#"><b style="font-size:120%">{{user.first_name.capitalize}} {{user.last_name.capitalize}}</b></a></li>
                    {% endif %}
                    <li class=""><a class="active" href="{% url 'index' %}"><b>Home</b></a></li>
                    <li><a class="" href="{% url 'App:about' %}"><b>About</b></a></li>
                    <li><a class="" href="{% url 'upload_file' %}"><b>File Upload</b></a></li>
                    <li><a class="" href="{% url 'file_delete' %}"><b>File Delete</b></a></li>
                    <li><a class="" href="{% url 'file_select' %}"><b>Predict</b></a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'App:update' pk=user.pk %}"><b>Update Profile</b></a>
                        </li>
                        <li>
                            <a href="{% url 'App:logout' %}"><b>Log Out</b></a>
                        </li>
                    {% else %}
                        <li>
                            {% if request.path == '/App/login/' %}
                                <a class="nav navbar-right" href="{% url 'App:register' %}"><span class="glyphicon glyphicon-user"><b style="font-size:150%">SignUp</b></span></a>
                            {% else %}
                                <a class="nav navbar-right" href="{% url 'App:login' %}"><span class="glyphicon glyphicon-user"><b style="font-size:150%">Login</b></span></a>
                            {% endif %}
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        <div class="content container">
            <div class="row">
                <div class="">
                    <div class="blog_posts">
                        {% block content %}

                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

App/templates/delete_success.html
{% extends "index.html" %}

{% block content %}
    <h5>
        File deleted with success!
    </h5>
{% endblock %}

App/templates/files_list.html
{% extends "index.html" %}

{% block content %}

{% for file in files_list %}

<p>{{ file }}</p>

{%endfor%}

{% endblock %}

App/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container">
    <center>
        <h1>Emotion Detection Using Speech Data</h1>
        <p>Analyzing the Emotion using the Speech Data</p>
        <br><br>
        <img src="{% static 'images/home.png' %}" alt="hello" height="55%" width="55%">
        <div class="jumbotron text-center" id="myJumbotron2" style="background-color:white">
            <div class="container" id="Container2">
              <div class="row">
                 <div class="col-sm-12 text-center" id="PredictionsOutput">
                 {% for pred in predictions %}
                   <h4>The emotion of the speaker in your file is: <strong>{{ pred }}</strong> </h4>
                 {% endfor %}
                 </div>
              </div>
            </div>
        </div>
    </center>
</div>
{% endblock %}

App/templates/post_file.html
{% extends "index.html" %}
{% load bootstrap3 %}
{% block content %}
    <br>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-primary">Upload file</button>
    </form>
{% endblock %}

App/templates/select_file_deletion.html
{% extends "index.html" %}

{% block content %}
<!--Here the number 2 in "/App/delete/2/" needs to be replaced with the pk of the file. The logic is working. -->
    <form action="/App/delete/" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <h5>Click confirm below the filename you want to delete from the following list:</h5>
        {% for myfile, pk in filename %}
            <p> - {{ myfile.filename }}</p>
            <input type="submit" value="Confirm">
            <input type="hidden" name="pk" value="{{ pk }}">
            <br>
            <br>
        {% endfor %}
        <br>
    </form>
{% endblock %}

App/templates/select_file_predictions.html
{% extends "index.html" %}

{% block content %}
    <form action="/App/predict/" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <h5>Please select one file at a time from the list of server files below.</h5>
        <h5>Clicking on the filename you can listen to the audio file.</h5>
        {% for myfile in filename %}
          <input type="checkbox" name="file_name" value="{{ myfile.filename }}">
            <label>
                <a href="/media/{{ myfile.filename }}">{{ myfile.filename }}</a>
            </label>
            <br>
        {% endfor %}
        <br>
        <button type="submit" class="btn btn-primary">Predict</button>
    </form>
{% endblock %}

App/templates/upload_success.html
{% extends "index.html" %}

{% block content %}
    <h5>
        File successfully uploaded!
    </h5>
{% endblock %}